version: '3'

services:

  app:
    build: .
    container_name: my_cont
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/wd
    ports:
      - ${PORT}:${PORT}

    depends_on:
      - db

  db:
    image: postgres:16.3
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    ports:
      - ${DB_PORT}:${DB_PORT}

volumes:
  postgres_data:

networks:
  default:
    driver: bridge

